### ISSUE TITLE
testtools should be a test extra requirement

### ISSUE THREAD

**Issue by exarkun** [testing-cabal/fixtures#38]
fixtures only needs testtools for its own test suite.  If a user of fixtures isn't interested in running the Fixtures test suite, they shouldn't have to install testtools as well.

**Comment by jelmer** [comment]
At a quick glance, it looks like even the core of fixtures uses testtools. E.g. fixtures/fixture.py imports from testtools.

**Comment by exarkun** [comment]
> At a quick glance, it looks like even the core of fixtures uses testtools. E.g. fixtures/fixture.py imports from testtools. It looks like those imports could fairly easily be removed though.

Yea, it does, doesn't it.  I'm not sure why I thought testtools was only used by the test suite.  I can't remember what context this came up in, either.

**Comment by cjwatson** [comment]
It's fairly easily removable, but it's also fairly easily removable from testtools (see testing-cabal/testtools#291).  Maybe we should do both!

**Comment by adeadman** [comment]
@cjwatson testtools still appears in requirements.txt and so when I install with pip using `--no-build-isolation` it complains about a missing testtools.
