### ISSUE TITLE
Failed to install fixtures 4.0.1 from pypi

### ISSUE THREAD

**Issue by hcindyl** [testing-cabal/fixtures#72]
pip errors out while running `pip install fixtures==4.0.1`

https://gist.github.com/hcindyl/427cc44f98ad879baf7aba26f31fd29a

Maybe because of the half-finished action in
https://github.com/testing-cabal/fixtures/runs/7155211005?check_suite_focus=true ?

**Comment by stephenfin** [comment]
I'll look into this though I will note that there's no wheel published on pypi for 4.0.1.

The CI failure isn't relevant. Someone must have pushed the release manually since that didn't even get that far

**Comment by jelmer** [comment]
That must have been me - I didn't realize the uploads to pypi are now automated. The release checklist in HACKING also still mentions uploading to pypi manually.

**Comment by stephenfin** [comment]
> That must have been me - I didn't realize the uploads to pypi are now automated. The release checklist in HACKING also still mentions uploading to pypi manually.

Yeah, I set things up to be but it's not working yet because I need to create a GitHub secret containing a PyPI token and only @rbtcollins has permission to do this. Until that happens, manual uploads are the right thing to do.
